### ISSUE TITLE
M1 Mac : Unable To Run | Version : 1.5.3.9

### ISSUE THREAD

**Issue by Ghostkwebb** [w-okada/voice-changer#516] opened 2023-07-21 17:32 UTC
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.10.zip

### OS

MacOS Sonoma

### GPU

M1 Pro

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

No

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Not sure

### Situation

I tried everything from the tutorial but this keeps happening. Do you know what I can do?
 

https://github.com/w-okada/voice-changer/assets/61558762/8aa394db-8b53-4831-808a-5170c9e28a8f

**Comment by Yasuo-San** [comment] 2023-07-21 18:23
1.5.3.10 doesn't work for mac currently, use 1.5.3.9.

**Comment by Ghostkwebb** [comment] 2023-07-22 07:20
So this is 1.5.3.9 and this problem keeps on occurring repeatedly.

https://github.com/w-okada/voice-changer/assets/61558762/4bfc0108-852a-40c4-81fc-8361d9c20204

**Comment by w-okada** [comment] 2023-07-22 22:59
Do your mac have microphone? GUI show none as device.

**Comment by Ghostkwebb** [comment] 2023-07-23 05:56
Ofc I have both internal and external microphone and it worked perfectly with older version of voice changer 1.5.3.5 I think. Well I deleted that thinking that 1.5.3.10 will work but anyways I have a normal M1 Pro with everything that the Mac has to offer.

**Comment by Cole404** [comment] 2023-07-24 14:07
> 
The same question. Have you solved it yet

**Comment by Cyclohexia** [comment] 2023-07-24 14:31
what does "dummied" mean actually

**Comment by w-okada** [comment] 2023-07-24 14:32
try latest version. v.1.5.3.10a

**Comment by ChinHongTan** [comment] 2023-07-24 14:36
Just for your information, v1.5.3.10a didn't work on M2 MacBook Pro.

**Comment by w-okada** [comment] 2023-07-24 14:44
I question, have you done this? It works in my environment. Therefore, I'm having trouble because I cannot replicate the situation where it doesn't work.

![image](https://github.com/w-okada/voice-changer/assets/48346627/c3e10cd1-3258-4fcc-bcf1-3cd5feab395b)

**Comment by Ghostkwebb** [comment] 2023-07-24 14:47
> one question. Have you done this? It works in my environment. Therefore, I'm having trouble because I cannot replicate the situation where it doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/48346627/255625008-c3e10cd1-3258-4fcc-bcf1-3cd5feab395b.png)

I think I showed this in the video but I will record once again with version 1.5.3.9 and show it to you here

**Comment by w-okada** [comment] 2023-07-24 15:19
Thank you everyone.
It indeed seems to be problematic. Could you please execute this .command? If available, it should produce a detailed log.

[startHttp2.zip](https://github.com/w-okada/voice-changer/files/12147437/startHttp2.zip)

**Comment by Ghostkwebb** [comment] 2023-07-24 15:28
<img width="682" alt="image" src="https://github.com/w-okada/voice-changer/assets/61558762/2a44ae5b-0d80-4a71-93ab-e99c80fbf6c4">

Here is what I got

**Comment by w-okada** [comment] 2023-07-24 15:30
Sorry, please extract MMVCSIO.xxx.zip to new folder and copy the .command file to the folder. Then run it.

**Comment by Ghostkwebb** [comment] 2023-07-24 15:30
lemme record the whole thing then

**Comment by Ghostkwebb** [comment] 2023-07-24 15:31
I need to run everything too right?

**Comment by w-okada** [comment] 2023-07-24 15:32
thanks, so, install _name_tool throw error...
What's this..

**Comment by w-okada** [comment] 2023-07-24 15:36
ok please.

**Comment by Ghostkwebb** [comment] 2023-07-24 15:43
> thanks, so, install _name_tool throw error... What's this..

idk :(

**Comment by Ghostkwebb** [comment] 2023-07-24 15:56
Here ya go 

https://github.com/w-okada/voice-changer/assets/61558762/4ac4931b-9be7-4617-b7bc-3b5271228ec0

**Comment by Ghostkwebb** [comment] 2023-07-24 16:02
oh ic ok will do that

**Comment by Ghostkwebb** [comment] 2023-07-24 16:09
Here ya go : 

https://github.com/w-okada/voice-changer/assets/61558762/2db07d6f-e80a-4b9d-b97d-6aeb83ccad9e

**Comment by w-okada** [comment] 2023-07-24 16:17
Thanks. It seems like the error has changed a bit.

> changes being made to file will invalidate the code signature in

I'll research it.

**Comment by w-okada** [comment] 2023-07-24 16:42
I'm sorry to bother you, but could you please cooperate with the experiment? Do you think it might work if you run this instead of the startHttp.command?

[startHttp3.zip](https://github.com/w-okada/voice-changer/files/12148094/startHttp3.zip)

**Comment by Ghostkwebb** [comment] 2023-07-24 16:43
Oh I will help u any way I can so that every fricking mac user can use it with ease lemme wuickly record and show ya

**Comment by Ghostkwebb** [comment] 2023-07-24 17:03
OMG Maybe u did it:


https://github.com/w-okada/voice-changer/assets/61558762/bb6b0f31-1687-4a16-8a1e-ae1a85a86c41


But the thing is when I tried speaking it sounded like aeaeaeaeaaaa


https://github.com/w-okada/voice-changer/assets/61558762/8833aa92-fc03-4683-9182-38c827df86da

**Comment by Ghostkwebb** [comment] 2023-07-24 17:12
Well this didn't happen in the old 1.5.3.5 version and it used to work with around 200 and now it's like this :) sorry for the trouble :) 

https://github.com/w-okada/voice-changer/assets/61558762/f6abc6a9-5412-4172-a4f6-6bdb496d2747

**Comment by w-okada** [comment] 2023-07-24 17:16
The sound quality isn't great, is it? Have you tried specifying a file as the input?

https://drive.google.com/file/d/1iCErRzCt5-6ftALcic9w5zXWrzVXryIA/view

**Comment by Ghostkwebb** [comment] 2023-07-24 17:20
<img width="872" alt="image" src="https://github.com/w-okada/voice-changer/assets/61558762/f5747673-4809-4416-ad82-d6c06e40434e">

I can't select vc though how do I put a file as input?

**Comment by Ghostkwebb** [comment] 2023-07-24 17:22
oooooof didn't see that aaa lemme do it now XD

**Comment by Ghostkwebb** [comment] 2023-07-24 17:29
https://github.com/w-okada/voice-changer/assets/61558762/dcf3cdaa-aab3-41e8-828b-713356d016c3

Well well well not the quality issue XD

**Comment by w-okada** [comment] 2023-07-24 17:32
I'm kind of lost here. Could you show me the terminal log, please?

**Comment by w-okada** [comment] 2023-07-24 17:33
please change f0 det to dio, and set S. Tresh to zero.

**Comment by w-okada** [comment] 2023-07-24 17:41
It's time to go to bed.　That's all for today...

**Comment by Ghostkwebb** [comment] 2023-07-24 17:42
Ok have a good night sleep it's time for bed for me too I'll just send it right now see it when u have time

**Comment by Ghostkwebb** [comment] 2023-07-24 17:43
https://github.com/w-okada/voice-changer/assets/61558762/33730313-6be5-41be-8f8a-41adaf018e57

**Comment by w-okada** [comment] 2023-07-25 01:56
@bundftd 
your cpu should not be M1/M2.

**Comment by w-okada** [comment] 2023-07-25 01:57
@bundftd 
Do you use m1 mac?

**Comment by kelvin-zhao** [comment] 2023-07-25 02:03
Is the v3 http finally working for Macs? 🤞🏻

**Comment by w-okada** [comment] 2023-07-25 03:38
I need more samples. Please try it

**Comment by Ghostkwebb** [comment] 2023-07-25 05:28
What is even happened I thought everything worked fine except the wierd audio thing

**Comment by Ghostkwebb** [comment] 2023-07-25 05:32
> c58657da-d123-418f-8baa-7b796ac44b8c.mp4

Also what about this?

**Comment by atrutlebtw** [comment] 2023-07-25 08:38
yeah im having similar audio issues when running v3

**Comment by Ghostkwebb** [comment] 2023-07-25 10:08
Ready for experiments!

**Comment by w-okada** [comment] 2023-07-25 10:45
I'm very grateful. However, I only have one idea right now. Please try using this .command.
[startHttp4.zip](https://github.com/w-okada/voice-changer/files/12160170/startHttp4.zip)

**Comment by ChinHongTan** [comment] 2023-07-25 11:03
I am able to run with v3, and by increasing chunk size (1024) I do not have any audio issues

**Comment by w-okada** [comment] 2023-07-25 11:15
Please try v4.

**Comment by atrutlebtw** [comment] 2023-07-25 11:17
will do

**Comment by Ghostkwebb** [comment] 2023-07-25 11:17
Gimme a second I will give it a try

**Comment by ChinHongTan** [comment] 2023-07-25 11:58
Can confirm v4 gets a big performance improvement over v3. With v3 I get res time between 1500-2000ms while v4 is around 400-500ms.

**Comment by atrutlebtw** [comment] 2023-07-25 12:03
yeah agreed, just no real voicing for me

**Comment by Ghostkwebb** [comment] 2023-07-25 13:19
> just white noise, gets slightly louder with microphone input, tried chunk sizes 512 - 2048 and dio, crepe and harvest, all with the same result also tried using a audio file instead of microphone, same result

It's working fine for you??

**Comment by Ghostkwebb** [comment] 2023-07-25 13:19
> Can confirm v4 gets a big performance improvement over v3. With v3 I get res time between 1500-2000ms while v4 is around 400-500ms.

I still get that wierd voice when trying

**Comment by w-okada** [comment] 2023-07-25 13:38
@Ghostkwebb 
1 question. Have you installed pytorch by yourself? (for the other application.) Perhaps, the previous pytorch may cause the result.

**Comment by Ghostkwebb** [comment] 2023-07-25 13:42
<img width="682" alt="image" src="https://github.com/w-okada/voice-changer/assets/61558762/41efff7e-b720-4637-bbca-debe3cfa62a4">

**Comment by w-okada** [comment] 2023-07-25 13:44
I see. However, it is a problem whether or not the previous version of PyTorch effects.

**Comment by Ghostkwebb** [comment] 2023-07-25 13:44
What should I do then?

**Comment by Ghostkwebb** [comment] 2023-07-25 13:52
Doesn't exist

**Comment by Ghostkwebb** [comment] 2023-07-25 13:52
<img width="682" alt="image" src="https://github.com/w-okada/voice-changer/assets/61558762/13f125e1-3f7f-416c-b763-c6373d188849">

**Comment by w-okada** [comment] 2023-07-25 13:53
really? so, previous pytorch is not cause... sorry.

**Comment by Ghostkwebb** [comment] 2023-07-25 15:06
WHAT

**Comment by Ghostkwebb** [comment] 2023-07-25 15:06
WHY ME GOD WHY ME!

**Comment by w-okada** [comment] 2023-07-25 15:20
I am generating experiment package with v4.
Let's check if there are others experiencing the same phenomenon.

**Comment by w-okada** [comment] 2023-07-25 15:22
The users in Simillar situation is here
https://github.com/w-okada/voice-changer/issues/339

**Comment by kelvin-zhao** [comment] 2023-07-26 02:18
v3 and v4 seems to work on Monterey, but I tried uploading a trained voice, the results doesn't seem to sound anything like it and it sounds pretty weird.

**Comment by w-okada** [comment] 2023-07-26 02:20
@kelvin-zhao 
how about sample model?

**Comment by kelvin-zhao** [comment] 2023-07-26 02:21
Yea, sample sounds really weird too, the pitch goes up and down, sounds really weird.

**Comment by w-okada** [comment] 2023-07-26 08:01
really?
I have a feeling that torchaudio isn't working very well, so I guess I'll have to consider not using it...

**Comment by w-okada** [comment] 2023-07-27 17:42
@dredot 
Sorry, instead of using startHttp.command, please use startHttpEnv.command.

**Comment by dredot** [comment] 2023-07-27 17:52
> 

<img width="568" alt="image" src="https://github.com/w-okada/voice-changer/assets/30910344/be94fa1d-6436-46e3-a388-40b5210a942b">

**Comment by w-okada** [comment] 2023-07-27 18:01
Did it not work out? I don't understand.

Could you please try using this .command file? If this doesn't work, I really won't know what to do next.
[startHttp5.zip](https://github.com/w-okada/voice-changer/files/12186489/startHttp5.zip)

I don't understand why I can't reproduce the bug in my own environment for the most part.

**Comment by dredot** [comment] 2023-07-27 18:42
> Did it not work out? I don't understand.
> 
> Could you please try using this .command file? If this doesn't work, I really won't know what to do next. [startHttp5.zip](https://github.com/w-okada/voice-changer/files/12186489/startHttp5.zip)
> 
> I don't understand why I can't reproduce the bug in my own environment for the most part.

for 11-alpha i am still getting the error  from above... i will go back to .9 and then i we can figure out if my computer is even capable to give us real time

**Comment by dredot** [comment] 2023-07-27 23:40
> Did it not work out? I don't understand.
> 
> Could you please try using this .command file? If this doesn't work, I really won't know what to do next. [startHttp5.zip](https://github.com/w-okada/voice-changer/files/12186489/startHttp5.zip)
> 
> I don't understand why I can't reproduce the bug in my own environment for the most part.

1.5.3.9 works just fine with your startHTTP update... the only problem i'm having now is a delay and then sometimes it goes in to a glitchy echo loop 

:-(

**Comment by Ghostkwebb** [comment] 2023-07-28 04:23
> Did it not work out? I don't understand.
> 
> Could you please try using this .command file? If this doesn't work, I really won't know what to do next. [startHttp5.zip](https://github.com/w-okada/voice-changer/files/12186489/startHttp5.zip)
> 
> I don't understand why I can't reproduce the bug in my own environment for the most part.

Which MacOS are you on @w-okada ?

**Comment by w-okada** [comment] 2023-07-28 04:28
<img width="575" alt="スクリーンショット 2023-07-28 13 27 16" src="https://github.com/w-okada/voice-changer/assets/48346627/0e7f2146-d287-4b8b-bcc8-007ce95276ec">

**Comment by Ghostkwebb** [comment] 2023-07-28 04:35
Well u should upgrade to ventura/sonoma cause I think most people are on it (at least the people here) and that's why you are unable to recreate the problem (I think at least)

**Comment by ramsemaj** [comment] 2023-07-28 07:44
when I ran startHttp5, it exited with 137 which is out of memory (according to the internet).  i get the same when trying to run manually.

```
% sh startHttp5.command
[Voice Changer] matplotlib is dummied
startHttp5.command: line 19:  4246 Killed: 9               PYTORCH_ENABLE_MPS_FALLBACK=1 MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO --https off -p 18888 --content_vec_500 pretrain/checkpoint_best_legacy_500.pt --content_vec_500_onnx pretrain/content_vec_500.onnx --content_vec_500_onnx_on true --hubert_base pretrain/hubert_base.pt --hubert_base_jp pretrain/rinna_hubert_base_jp.pt --hubert_soft pretrain/hubert-soft-0d54a1f4.pt --nsf_hifigan pretrain/nsf_hifigan/model --crepe_onnx_full pretrain/crepe_onnx_full.onnx --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx --rmvpe pretrain/rmvpe.pt --model_dir model_dir --samples samples.json

% echo $?                                        
137

```

**Comment by NBNew** [comment] 2023-07-28 16:13
> I tried creating a version without using torchaudio as an experiment. Could you give it a try?
> 
> https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha.zip

Hey @w-okada , I would like to inform you that it indeed worked with with demo ( without torchaudio ), however the voice is soo choppy that it's difficult to understand even a single word and  I guess thats expected since torchaudio is missing ? For reference, I am on attached version 
<img width="222" alt="image" src="https://github.com/w-okada/voice-changer/assets/137643794/e2f89270-fff2-48f3-8824-1478d237b24c">
<img width="691" alt="image" src="https://github.com/w-okada/voice-changer/assets/137643794/55327c30-872d-4534-bfe3-7b1396bb7f8d">

**Comment by Ghostkwebb** [comment] 2023-07-28 16:18
> > I tried creating a version without using torchaudio as an experiment. Could you give it a try?
> > https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha.zip
> 
> Hey @w-okada , I would like to inform you that it indeed worked with with demo ( without torchaudio ), however the voice is soo choppy that it's difficult to understand even a single word and I guess thats expected since torchaudio is missing ? For reference, I am on attached version <img alt="image" width="222" src="https://user-images.githubusercontent.com/137643794/256874895-e2f89270-fff2-48f3-8824-1478d237b24c.png"> <img alt="image" width="691" src="https://user-images.githubusercontent.com/137643794/256874978-55327c30-872d-4534-bfe3-7b1396bb7f8d.png">

Does it sound like this?
https://user-images.githubusercontent.com/61558762/255915277-a828824b-350d-4829-af26-c3904b12d6fd.mp4

**Comment by NBNew** [comment] 2023-07-28 16:27
> > > I tried creating a version without using torchaudio as an experiment. Could you give it a try?
> > > https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha.zip
> > 
> > 
> > Hey @w-okada , I would like to inform you that it indeed worked with with demo ( without torchaudio ), however the voice is soo choppy that it's difficult to understand even a single word and I guess thats expected since torchaudio is missing ? For reference, I am on attached version <img alt="image" width="222" src="https://user-images.githubusercontent.com/137643794/256874895-e2f89270-fff2-48f3-8824-1478d237b24c.png"> <img alt="image" width="691" src="https://user-images.githubusercontent.com/137643794/256874978-55327c30-872d-4534-bfe3-7b1396bb7f8d.png">
> 
> Does it sound like this? https://user-images.githubusercontent.com/61558762/255915277-a828824b-350d-4829-af26-c3904b12d6fd.mp4

That was sooo funny :D , it's like someone is humming. No, for me I have the wordings but its not clear enough, not tuned. May be something to do with settings. Could you recommend some settings to try out ?

**Comment by Ghostkwebb** [comment] 2023-07-28 16:28
Damn it really is a macOS sonoma problem ooof

**Comment by NBNew** [comment] 2023-07-28 16:29
> Damn it really is a macOS sonoma problem ooof

but the other versions didn't work for me, got dummied related error while starting it. Please recommend good settings if possible, I would like to see if its perfectly working with v11 or not

**Comment by yeodakyum** [comment] 2023-07-28 16:35
also having problem with me, macOS 13.4, v1.5.3.10 so not macOS sonoma problem.

**Comment by NBNew** [comment] 2023-07-28 16:36
And I can't check for any other version, not even v1.5.3.9 but no matter which version link you click, it goes to v1.5.3.10 only

**Comment by Ghostkwebb** [comment] 2023-07-28 16:45
I really don't know what the humming problem is and how to fix it. AAAAAA why did I delete the old version :(

**Comment by NBNew** [comment] 2023-07-28 16:48
> 

Don't worry, it's not working for us as well. I could just install the demo version but it's of no use

**Comment by NBNew** [comment] 2023-07-28 18:27
QuickUpdate, now I can't launch the app. Stuck with same error like before

**Comment by w-okada** [comment] 2023-07-28 20:51
https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha2.zip

**Comment by Ghostkwebb** [comment] 2023-07-28 20:51
I'll try this

**Comment by NBNew** [comment] 2023-07-28 21:08
> https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha2.zip

Thanks a ton for fixing this @w-okada , I spent hours trying to install it using python code and was able to complete it. I confirm that the app is launching now, however I observed that it keeps repeating the first sentence in loop and the voice ie very choppy. Is there any issue or due to some setting ? 
<img width="559" alt="image" src="https://github.com/w-okada/voice-changer/assets/137643794/b0ddf4a8-80cb-48c2-b056-ef138b5d22f1">

**Comment by w-okada** [comment] 2023-07-28 21:13
MBA/MBP's microphone is very high performance. so the mic catch audio output and convert it repeatedly. 
Use a headphone. or Use virtual cable to avoid

**Comment by Ghostkwebb** [comment] 2023-07-28 21:25
is there truly no fix for that humming?

**Comment by w-okada** [comment] 2023-07-28 21:27
Is alpha2 not working properly even when you use it?

**Comment by NBNew** [comment] 2023-07-28 21:33
Fantastic, with headset its way better however still there are some disconnects, not sure if it's supposed to be as I have installed it for the first time but knew about this awesome VC. Thank you once again for all your hard work, appreciate it!!

**Comment by w-okada** [comment] 2023-07-28 21:35
Increase chunk size and use dio. MPS is not better than nvidia gpu.

**Comment by Ghostkwebb** [comment] 2023-07-28 21:46
> Is alpha2 not working properly even when you use it?

Well, I tried alpha 2 but the humming thing still happens. I am literally unable to figure out what the problem is AAAAAAAAAAA

**Comment by dredot** [comment] 2023-07-28 22:09
One last question for the new models do we need to use RVC or will RVCv2 work as well?

**Comment by dredot** [comment] 2023-07-28 22:11
> One last question for the new models do we need to use RVC or will RVCv2 work as well?

/

**Comment by dredot** [comment] 2023-07-28 22:13
> https://huggingface.co/wok000/vcclient000/resolve/main/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.11_alpha2.zip

this one worked for me:

Macbook Pro 2021 
M1 Pro 
Ventura 13.4.1 

My other question is, when you're importing models, does it have to be ONLY RVC or can i use RVC_v2?

**Comment by w-okada** [comment] 2023-07-28 22:22
RVCv2 is supported.

**Comment by w-okada** [comment] 2023-07-29 13:42
Thank you everyone. It seems to be running on M1 Macs for a number of people. For now, we will close this issue. As for Sonoma, it doesn't seem to work, so let's continue the discussion in this issue.

https://github.com/w-okada/voice-changer/issues/591

**Closed by w-okada** 2023-07-29 13:42 UTC

**Comment by Mr4ucker** [comment] 2023-11-16 10:49
Sorry, the question is, will the program run on a macbook pro 2015?
