### ISSUE TITLE
Blackscreen during using 

### ISSUE THREAD

**Issue by habib337** [w-okada/voice-changer#563] opened 2023-07-26 11:24 UTC
### Issue Type

Bug Report

### vc client version number

 MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip

### OS

windows 11

### GPU

GTX 1650

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX 

### Situation

my voice changer its going very very well, work fine,  but after 30 minutes my monitor become blackscreen with no cursor mouse, and the worst nightmare i cant shutdown my pc even after pressing the power button,

**Comment by w-okada** [comment] 2023-07-26 20:07
That's a phenomenon I've never heard of before. Let's see if there's anyone who has experienced something similar.

Perhaps the temperature of the PC is too high, causing it to overheat. But I'm not sure.

**Comment by habib337** [comment] 2023-07-27 03:05
thank you for reply okada, but its not pc to high , my gpu still normal, i dont know too what problem

**Comment by habib337** [comment] 2023-07-27 17:30
> 

I tried reinstall in another folder but when i try start again it all I get is a black screen. I tried re-downloading but it still does the same. Any advice?

**Comment by w-okada** [comment] 2023-07-28 20:11
are there no logs in terminal?

**Comment by Arizona-dev** [comment] 2023-07-28 21:13
I’m not familiar with the project yet but could it be an issue with the VRAM of the gpu? 
Could you monitor it until it goes dark again and see if it’s full or not ?

**Comment by habib337** [comment] 2023-07-28 23:29
> are there no logs in terminal?

my setting and voice changer work very well, but after using 30 minutes my monitor become blackscreen without cursor mouse, i cant see anyting, my keyboard too cant work and i cant shutdown my pc

**Comment by habib337** [comment] 2023-07-28 23:32
> I’m not familiar with the project yet but could it be an issue with the VRAM of the gpu? Could you monitor it until it goes dark again and see if it’s full or not ?

Only thing I could think of would be either some driver conflicts or the system running out of resources like RAM or VRAM. Crashes due to running out of RAM is very rare though as Windows will usually manage it afaik.

**Comment by habib337** [comment] 2023-07-31 01:27
> I’m not familiar with the project yet but could it be an issue with the VRAM of the gpu? Could you monitor it until it goes dark again and see if it’s full or not ?

its full dark, horibble i cant shutdown my pc, my keyboard or my mouse doesnt work, but my pc still runinng

**Comment by w-okada** [comment] 2023-08-01 03:01
I have no idea. 
Have you check performance monitor to ckeck vram usage?

**Comment by habib337** [comment] 2023-08-01 03:13
> I have no idea. Have you check performance monitor to ckeck vram usage?

yes arleady see vram usage only 2gb, i see on task manager 

maybe because my gpu so low end ? i only using gtx 1650 with vram 4gb

**Comment by w-okada** [comment] 2023-08-01 03:18
There are people running it on a GTX 1650, but it's unclear whether they're able to run it for over 30 minutes.

**Comment by habib337** [comment] 2023-08-01 03:36
> There are people running it on a GTX 1650, but it's unclear whether they're able to run it for over 30 minutes.

maybe its from my Ram ? i have mobo A320m pro m2 v2 (cant overclock or xmp profile) i have ram 16gb but its not same mhz, 2400mhz and 2666mhz, maybe driver conflicts or the system running out of resources like RAM or VRAM ?

**Comment by habib337** [comment] 2023-08-02 08:33
> > the system running out of resources like RAM or VRAM ?
> > I think no. You said performance monitor show 2gb usage of vram. But I have no idea why.

i have no idea too, maybe its from my cpu ? because i using AMD ryzen 5 2400g does the cpu also affect performance??

**Comment by w-okada** [comment] 2023-08-06 14:28
any update?

**Comment by habib337** [comment] 2023-08-07 02:31
> any update?

arleady update latest version, but now after 45 minutes my monitor become blackscreen without cursor mouse

**Comment by w-okada** [comment] 2023-08-07 17:39
However, there are no reports similar to your situation. I afraid it depends on your specific circumstances. I think it would be a good idea to prepare a new computational environment. For now, since there is nothing we can do, we will close the issue.

**Closed by w-okada** 2023-08-07 17:39 UTC

**Comment by User7819** [comment] 2023-09-17 09:15
I had exactly the same problem. 
This issue caused by gpu overheating!

Give a very good cleaning to your PC, and apply new thermal paste.
It worked for me
